### ISSUE TITLE
Capitalization in generated SQL

### ISSUE THREAD

**Issue by asherber** [d-p-y/statically-typed-poco-queries#1]
It would be nice if the generated SQL uppercased the reserved words WHERE, AND and OR were uppercased, following usual conventions. I can prepare a PR if you are okay with this.

**Comment by d-p-y** [comment]
Hi @asherber, sure I'm open to improvements! I would also very happily accept other improvements such as making it target different dotnet frameworks.

**Comment by asherber** [comment]
Excellent, thanks! I've submitted two PRs for your consideration.
