### ISSUE TITLE
Column name from [Column] attribute

### ISSUE THREAD

**Issue by asherber** [d-p-y/statically-typed-poco-queries#6]
`comparisonToWhereClause` doesn't take explicit column names into account, and it would be nice if it did.

```csharp
private class MyClass
{
    public int ID { get; set; }
    [Column("Foo")]
    public string Name { get; set; }
}

db.Query<MyClass>(c => c.Name == "Bar");
// Result: WHERE [Name] = 'Bar'
// Should be: WHERE [Foo] = 'Bar'
```

It looks like the various xPoco classes all use an attribute called `Column` for this, so it should be sufficient to look for that attribute in particular. (An improvement would be overloads that take a `Type` argument, so the user can specify which attribute to look at for names.)

I would offer to help with a PR, but I'm much more a C# guy than an F# guy -- though it does look like the issue is with `body.Member.GetType().Name` at line 45.

**EDIT:** No, I guess it's line 50. Instead of just passing in the member name, the function should go back to the member on the class and look for a `Column` property.

**Comment by d-p-y** [comment]
Hi @asherber,
Can you please have a look at the proposal in branch? I think it is generic enough to support all *poco libraries. OK for you?
For clarity - tests are not finished yet. Still, by looking at ```TestUsesCustomNameExtractors()``` you can see the idea for the API.
Thanks

**Comment by asherber** [comment]
So the idea is that each library of bindings for a specific *Poco flavor would declare its own custom name extractor, referencing its own `Column` attribute? That should work.

I was thinking you could define a single name extractor, using reflection to look for an attribute named `ColumnAttribute` and then getting the value of its `Name` property. The three big *Pocos that I'm aware of (Peta, N, Async) all use that convention, and I'll bet the smaller ones do as well. But I guess it makes sense to leave it entirely up to the bindings.

Thanks for looking into this so quickly!

**Comment by d-p-y** [comment]
Hi @asherber,
Regarding implementation - I think current implementation is better despite that it requires a little bit of code on your side (providing extraction function). I wanted to avoid 'guessing' when it can be sensibly avoided. Additionally, current approach gives better performance (look for precise custom attribute class by type _versus_ look for custom attribute by string). 

Anyway: feature is added, v1.9.0.0 contains it, it's already uploaded to nuget.

**Comment by asherber** [comment]
Yup, sounds good to me -- thanks for looking into this so quickly!
