### ISSUE TITLE
Questionable behaviour from ExpressionToSql.Translate

### ISSUE THREAD

**Issue by nj-db** [d-p-y/statically-typed-poco-queries#7]
Hi,

I am contacting you because I noticed some behaviour while using the StaTypPocoQueries.Core & StaTypPocoQueries.PetaPoco that I don't think is expected behaviour.

If I run the following code I get two differing results:

`
var testClass = new { TestColumn = "test" };
var testColumn = "test";

var database = new Database("dummyConnection", new SqlServerDatabaseProvider());
            
var sql1 = Build<TestClass>(o => o.TestColumn == testClass.TestColumn, database).SQL;
var sql2 = Build<TestClass>(o => o.TestColumn == testColumn, database).SQL;

private static Sql Build<T>(Expression<Func<T, bool>> query, IDatabase database)
{
     var result = ExpressionToSql.Translate(new DatabaseQuoter(database), query, true);
     return new Sql(result.Item1, result.Item2);
}
`

sql1 = "WHERE [TestColumn] = [TestColumn]"
sql2 = "WHERE [TestColumn] = @0"

For both of these results I would have expected it to be "WHERE [TestColumn] = @0" because for both queries I would expect the query to be using the value of the right side of the tests not the actual column name. That is the behaviour that you get with regular Linq queries and I would expect that it would also be the same for Linq to SQL predicates as well.

What concerns me about the the sql1 result is that it is a test that returns all rows in a given table and I have found it also has an outcome of deleting all rows in a table instead of just deleting the rows in the table where TestColumn equals 'test'.

Is the translation of the query into sql1 expected behaviour?

**Comment by d-p-y** [comment]
Hi nj-db
Thank you for reporting this issue. Currently expression-to-sql-string logic only deals with constant values, variables and member access as far as I remember. It should be extended to differentiate between member access to expression parameter AND member access to arbitrary variable (as it is the case in your example). At this moment it doesn't consider it thus you end up with this unfortunate result. I'll try to look at it ASAP as it indeed seems to be a gotcha. Hope it didn't cause you too much trouble.

**Comment by d-p-y** [comment]
fixed and released as v1.11.0

**Comment by nj-db** [comment]
Hi @d-p-y 
I have checked my tests of ExpressionToSql.Translate with the new version of the package and the behavior is as expected now. Thanks for addressing this issue so promptly.
