### ISSUE TITLE
Mapping names and values

### ISSUE THREAD

**Issue by asherber** [d-p-y/statically-typed-poco-queries#9]
@d-p-y Just a heads up. I realized yesterday while working on another project with PetaPoco that focusing on column and converter attributes for names and values misses the bigger picture. In addition to attributes, I think all the *Poco variants use a mapper to handle translations between POCOs and the database; the mapper uses the attributes on POCOs, but it can also perform other transforms. 

In the latest version of [StaTypPocoQueries.PetaPoco](https://github.com/asherber/StaTypPocoQueries.PetaPoco) I have updated my code to let the mapper for the type do the work, instead of just looking for attributes myself.

**Comment by d-p-y** [comment]
Glad to hear that you were able to generalize it. Thanks
